services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: weather_forecast:latest
    container_name: weather_forecast
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
    environment:
      - DEBUG=True
    command: >
      sh -c "cd /app &&
            python manage.py migrate --noinput &&
            python manage.py collectstatic --noinput &&
            python manage.py runserver 0.0.0.0:8000"

volumes:
  static_volume: